name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout projeto
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Instalar dependências
        run: |
          npm install
          npm install -D typescript

      - name: Preparar pasta www
        run: |
          rm -rf www
          mkdir -p www
          cp index.html manifest.webmanifest service-worker.js www/
          cp -r assets src www/

      - name: Criar capacitor.config.ts
        run: |
          cat > capacitor.config.ts <<'EOF'
          import type { CapacitorConfig } from '@capacitor/cli';

          const config: CapacitorConfig = {
            appId: 'rjp.eixooeste.amv',
            appName: 'Eixo Oeste AMV',
            webDir: 'www'
          };

          export default config;
          EOF

      - name: Criar Android
        run: |
          rm -rf android
          npx cap add android
          npx cap sync android

      - name: Aceitar licenças Android
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Instalar SDK Platform 36
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          "platforms;android-36" \
          "build-tools;35.0.0"

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Eixo_Oeste_AMV_RJP_debug_apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
